/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package login;

import Admin.Administrator;
import I_manager.InventoryManager;
import S_manager.SalesManager;
import S_men.SalesMen;
import com.sun.glass.events.KeyEvent;
import connections.DB_Connect;
import homes.Home_Ad;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
//import static login.textMove.final2;



  




/**
 *
 * @author chathura93
 */
public class login2 extends javax.swing.JFrame
{

    Connection  con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    
    private Timer tme;
    int count;
    public final static int TWO_SECOND=5;
    int id=0;
    
    
    public login2() {
        initComponents();
        setDate();
        bar.setVisible(false);
        con = DB_Connect.getConnection();
        colorChange();
    }
    
    
    class TimerListener implements ActionListener{
        
        public void actionPerformed(ActionEvent ae) {
            bar.setVisible(true);
            count++;
            bar.setValue(count);
            if(count==101){
                tme.stop();
                progress();
                if(id==1){
                    SalesMen smen = new SalesMen();
                    smen.setVisible(true);
                    setVisible(false);
                }
                else if(id==2){
                    SalesManager smgr = new SalesManager();
                    smgr.setVisible(true);
                    setVisible(false);
                }
                else if(id==3){
                    InventoryManager imgr = new InventoryManager();
                    imgr.setVisible(true);
                    setVisible(false);
                }
                else if(id==4){
                    Administrator admin = new Administrator();
                    admin.setVisible(true);
                    setVisible(false);
                }
                 
            }
        }
        
    }
    
    public void progress(){this.setVisible(false);}
    public void activate(){tme.start();}
   
    
    
    
    
    private void setDate(){
       // SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
       // lg_date.setText(dte);
        
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
        Date today = Calendar.getInstance().getTime();
        String dateAsString = dateFormatter.format(today);
        String timeAsString = timeFormatter.format(today);
        lgTime.setText(timeAsString);
        lgDate.setText(dateAsString);
        
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEEEEEEE", Locale.US); 
        String asWeek = dateFormat.format(now);
        stringDay.setText(asWeek);
        //lg_date.setText(dateAsString);
    }
    

   
    
    
    private void colorChange(){
    
        this.jPanel1.setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stringDay = new javax.swing.JLabel();
        lgDate = new javax.swing.JLabel();
        lgTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        bar = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        stringDay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stringDay.setForeground(new java.awt.Color(255, 255, 255));
        stringDay.setText("123");
        jPanel1.add(stringDay);
        stringDay.setBounds(600, 390, 70, 20);

        lgDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lgDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lgDate);
        lgDate.setBounds(660, 410, 80, 20);

        lgTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lgTime.setForeground(new java.awt.Color(255, 255, 255));
        lgTime.setText("123");
        jPanel1.add(lgTime);
        lgTime.setBounds(680, 390, 70, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(700, 370, 40, 14);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 290, 80, 30);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(280, 240, 290, 30);

        bar.setBackground(new java.awt.Color(51, 255, 51));
        bar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(bar);
        bar.setBounds(160, 400, 300, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(280, 200, 290, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password   :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 240, 120, 30);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 200, 110, 20);

        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Password :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 50, 510, 230);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setText("A.P.M.R INVENTORY CONTROL SYSTEM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 20, 710, 90);

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-430, 80, 760, 440);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 300, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         String password;
         password = new String(jPasswordField1.getPassword());
         String u_type = "SELECT User_Type_Name from user WHERE Username = '"+jTextField1.getText()+"'";
        
      
        String sql1 = "SELECT * FROM user where Username=? and password=?";
       
        try {
            
            pst = con.prepareStatement(u_type);
            rs = pst.executeQuery();
            String type = null;
            while(rs.next()){
                type = rs.getString("User_Type_Name");
            }
            
            
             
            pst = con.prepareStatement(sql1);
            pst.setString(1, jTextField1.getText());
            pst.setString(2,password );
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                
                if(type.equals("Salesmen")){
                    //System.out.println(type);
                    id=1;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    
                    //SalesMen smen = new SalesMen();
                   // smen.setVisible(true);
                   // this.dispose();
                 
                    
               }else if(type.equals("Sales Manage")){
                   id=2;
                   count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    
                } else if(type.equals("Inventory Manager")){
                    id=3;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    
                }else if(type.equals("Administrator")){
                    id=4;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    
                
                }
               
            
                
            }else{
                JOptionPane.showMessageDialog(null,"Invlaid user name and password");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
               String password;
         password = new String(jPasswordField1.getPassword());
         
        String u_type = "SELECT User_Type_Name from user WHERE Username = '"+jTextField1.getText()+"'";
        
  
        String sql1 = "SELECT * FROM user where Username=? and password=?";
       
        try {
            
             pst = con.prepareStatement(u_type);
            rs = pst.executeQuery();
            String type = null;
            while(rs.next()){
                type = rs.getString("User_Type_Name");
            }
            
            
             
            pst = con.prepareStatement(sql1);
            pst.setString(1, jTextField1.getText());
            pst.setString(2,password );
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                
                if(type.equals("Salesmen")){
                    //System.out.println(type);
                    id=1;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    
                    //SalesMen smen = new SalesMen();
                   // smen.setVisible(true);
                   // this.dispose();
                 
                    
               }else if(type.equals("Sales Manage")){
                   id=2;
                   count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    //SalesManager smgr = new SalesManager();
                   // smgr.setVisible(true);
                   // this.dispose();
                } else if(type.equals("Inventory Manager")){
                    id=3;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    //InventoryManager imgr = new InventoryManager();
                   // imgr.setVisible(true);
                    //this.dispose();
                }else if(type.equals("Administrator")){
                    id=4;
                    count=-1;
                    bar.setValue(0);
                    bar.setStringPainted(true);
                    tme = new Timer(TWO_SECOND,new TimerListener());
                    activate();
                    //Administrator admin = new Administrator();
                   // admin.setVisible(true);
                    //this.dispose();
                
                }
               
            
                
            }else{
                JOptionPane.showMessageDialog(null,"Invlaid user name and password");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
        
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login.NewJPanel test = new login.NewJPanel();
        test.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lgDate;
    private javax.swing.JLabel lgTime;
    private javax.swing.JLabel stringDay;
    // End of variables declaration//GEN-END:variables
}


